### ISSUE TITLE
problem of Securing WHMCS

### ISSUE THREAD

**Issue by jsjcjsjc** [rrpproxy/whmcs-rrpproxy-registrar#78] opened 2022-02-22 03:27 UTC
I am reading the words below
https://centralnic-reseller.github.io/centralnic-reseller/docs/rrpproxy/whmcs/whmcs-rrpproxy-registrar/#securing-whmcs

it said
```
Give the following locations read, write and delete permissions:
Contact
Dns
Domain
Domainapplication
Nameserver
```

but I didn't find **DNS** in rrpproxy.net permissions page, could you please help me on it ?
Thanks

**Comment by papakai** [comment] 2022-02-22 12:01
Would you mind opening a Support Ticket at https://www.rrpproxy.net/Contact/Contact_Form to get this issue addressed? Please provide there your RRPproxy account name as well for faster processing.

This problem is not directly related to our whmcs integrations and has to be processed over the Standard Support way. Still, be so kind as to know us the results in here.

**Comment by papakai** [comment] 2022-03-10 13:44
@jsjcjsjc I did not hear back from you. As this issue is not a bug of the integration itself I have to close this bug report. If this problem still exists, please reach out to standard support as mentioned. If you already did this, it would be great to know about the results - add them here then.

Enjoy your day!

**Closed by papakai** 2022-03-10 13:44 UTC
Labels: documentation, question

**Comment by papakai** [comment] 2022-04-08 12:58
How did you now received access to the DNS part? Would be great if you could provide that feedback @jsjcjsjc. Thanks.

**Comment by jsjcjsjc** [comment] 2022-04-08 14:19
> How did you now received access to the DNS part? Would be great if you could provide that feedback @jsjcjsjc. Thanks.

I have no idea, after opening a ticket, the DNS option appeared in the page
